/**
 * Project Chronos — Documentary Master Composition
 *
 * Root Remotion composition that assembles all visual layers:
 * - Ken Burns Canvas (background visual asset)
 * - Map Visualizer (for MAP overlay scenes)
 * - Graphic Overlays (NEWSPAPER, STAT_COUNTER)
 * - Kinetic Captions (word-level highlighted subtitles)
 * - Film Grade (cinematic LUT, grain, vignette)
 * - Voiceover audio sequences
 *
 * The composition is driven by a ProjectChronosManifest JSON file
 * generated by the Python backend pipeline.
 */

import React, { useMemo } from "react";
import { AbsoluteFill, Sequence, Audio, useVideoConfig, staticFile } from "remotion";
import type { ProjectChronosManifest } from "../types/schema";
import { KenBurnsCanvas } from "../components/KenBurnsCanvas";
import { KineticCaptions } from "../components/KineticCaptions";
import { MapVisualizer } from "../components/MapVisualizer";
import { GraphicOverlays } from "../components/GraphicOverlays";
import { FilmGrade } from "../components/FilmGrade";
import { MasterFilmGrade } from "../components/MasterFilmGrade";
import { ParallaxLayer } from "../components/ParallaxLayer";
import { scenesWithTiming } from "../types/schema";

export interface DocumentaryMasterProps {
  /** The complete project manifest */
  manifest: ProjectChronosManifest;
  /** Optional background music track path */
  bgmPath?: string;
  /** Optional style overrides */
  styleOverrides?: {
    filmGrain?: number;
    vignette?: number;
    lut?: string;
  };
}

/**
 * DocumentaryMaster — The root composition for Project Chronos.
 *
 * Assembles the complete documentary timeline from the manifest,
 * rendering each scene as a sequence with:
 * - Background visual (Ken Burns / Parallax / Map)
 * - Overlay graphics (newspaper, stat counters, maps)
 * - Kinetic captions synced to audio timestamps
 * - Post-processing (film grade, grain, vignette)
 */
export const DocumentaryMaster: React.FC<DocumentaryMasterProps> = ({
  manifest,
  bgmPath,
  styleOverrides,
}) => {
  const { width, height, fps } = useVideoConfig();
  const scenes = useMemo(() => scenesWithTiming(manifest), [manifest]);

  // Resolve the static file path for an asset
  // Use Remotion's staticFile() which registers files from the public dir
  // For file:// URLs, return them directly (they shouldn't be passed through staticFile)
  const resolveAssetPath = (uri: string): string => {
    if (!uri) return "";
    // HTTP URLs, absolute paths, and file:// URLs are returned as-is
    if (uri.startsWith("/") || uri.startsWith("http://") || uri.startsWith("https://") || uri.startsWith("file://")) {
      return uri;
    }
    // For relative paths, use staticFile (registered from public dir)
    return staticFile(uri);
  };

  return (
    <AbsoluteFill
      style={{
        backgroundColor: "#050505",
        overflow: "hidden",
        width: "100%",
        height: "100%",
      }}
    >
      {/* ─── Visual Layers ─── */}
      {scenes.map((scene) => {
        const visualAsset = scene.visual_asset;
        const assetPath = resolveAssetPath(visualAsset.asset_uri);
        const isImage =
          visualAsset.source_type === "STOCK_IMAGE" ||
          visualAsset.source_type === "AI_GENERATED" ||
          visualAsset.source_type === "GRAPHIC_OVERLAY";
        const isMap =
          visualAsset.source_type === "MAP_ANIMATION" ||
          visualAsset.overlay_spec.type === "MAP";

        return (
          <Sequence
            key={scene.scene_id}
            from={scene.start_frame}
            durationInFrames={scene.duration_frames}
          >
            {/* Background Visual Asset */}
            {assetPath && !isMap && (
              <>
                {visualAsset.motion_preset === "PARALLAX_DRIFT" ? (
                  <ParallaxLayer
                    src={assetPath}
                    type={isImage ? "image" : "video"}
                    durationInFrames={scene.duration_frames}
                    sceneStartFrame={scene.start_frame}
                  />
                ) : (
                  <KenBurnsCanvas
                    src={assetPath}
                    type={isImage ? "image" : "video"}
                    motionPreset={visualAsset.motion_preset}
                    durationInFrames={scene.duration_frames}
                    sceneStartFrame={scene.start_frame}
                    muted
                  />
                )}
              </>
            )}

            {/* Background placeholder when no asset */}
            {!assetPath && !isMap && (
              <AbsoluteFill
                style={{
                  backgroundColor:
                    scene.act_type === "HOOK"
                      ? "#1a0a0a"
                      : scene.act_type === "CLIMAX"
                      ? "#2a0a1a"
                      : "#0a0a1a",
                  background: `radial-gradient(circle at center, ${
                    scene.act_type === "HOOK"
                      ? "#4a2a2a"
                      : scene.act_type === "CLIMAX"
                      ? "#5a2a4a"
                      : "#1a2a4a"
                  } 0%, transparent 70%)`,
                }}
              />
            )}

            {/* Map Visualizer (for MAP overlay type) */}
            {visualAsset.overlay_spec.type === "MAP" && (
              <MapVisualizer
                overlaySpec={visualAsset.overlay_spec}
                startFrame={scene.start_frame}
                durationInFrames={scene.duration_frames}
              />
            )}

            {/* Graphic Overlays (NEWSPAPER, STAT_COUNTER) */}
            {visualAsset.overlay_spec.type !== "NONE" &&
              visualAsset.overlay_spec.type !== "MAP" && (
                <GraphicOverlays
                  overlaySpec={visualAsset.overlay_spec}
                  startFrame={scene.start_frame}
                  durationInFrames={scene.duration_frames}
                  width={width}
                  height={height}
                />
              )}

            {/* Kinetic Captions */}
            <KineticCaptions
              captions={scene.captions}
              startFrame={scene.start_frame}
              durationInFrames={scene.duration_frames}
              fontSize={Math.round(height * 0.045)}
              maxWidth={80}
            />
          </Sequence>
        );
      })}

      {/* ─── Audio Layers ─── */}
      {manifest.scenes.map((scene) => (
        <Sequence
          key={`audio-${scene.scene_id}`}
          from={scene.start_frame}
          durationInFrames={scene.duration_frames}
        >
          <Audio
            src={scene.voiceover.audio_path.startsWith("file://") ? scene.voiceover.audio_path : staticFile(scene.voiceover.audio_path)}
            volume={1.0}
          />
        </Sequence>
      ))}

      {/* Background Music */}
      {bgmPath && (
        <Audio src={bgmPath} volume={0.45} />
      )}

      {/* ─── Post-Processing Layer (applies to entire timeline) ─── */}
      <AbsoluteFill
        style={{
          pointerEvents: "none",
        }}
      >
        <MasterFilmGrade
          lut={(styleOverrides?.lut as any) || "teal-orange"}
          vignetteStrength={styleOverrides?.vignette || 0.45}
          grainOpacity={styleOverrides?.filmGrain || 0.07}
          letterbox={true}
          letterboxRatio="2.35:1"
        />
      </AbsoluteFill>
    </AbsoluteFill>
  );
};
